#!/bin/bash
SCRIPT_DIR="${1%/*}/package.hook/${EBUILD_PHASE}/${CATEGORY}/${PN}"
if [ -d "${SCRIPT_DIR}" ]; then
	if compgen -G "${SCRIPT_DIR}/*"; then
		for scripts in "${SCRIPT_DIR}/"*; do
			bash "$scripts"
		done
	else
		einfo "Directory \"${SCRIPT_DIR}\" exists but no hooks are inside!"
	fi
fi
