#!/bin/sh

## Core functions to make plugin manager less location-dependent

# Set up import function then load the env cleaner
import() {
	if [ "$(mapfile -tn "1" shebang < "$portageDir/core/$1" && printf "$shebang")" == "#!/bin/sh" ]; then
		infoDbg "Importing shell component $1"
		source "$portageDir/core/$1"
	else
		infoDbg "Importing binary component $1"
		"$portageDir/core/$1"
	fi
}
import libraries/envcleaner
